// ========== 大阿卡那 ==========
export const MAJOR = [
  ["9/90/RWS_Tarot_00_Fool.jpg","愚者","The Fool","全新开始，勇敢冒险","鲁莽行事，考虑不周","A fresh start, a bold leap of faith","Recklessness, acting without thought",
    "今天适合放下过多算计，跟着直觉往前迈一步；哪怕看不清终点，行动本身就会带来转机。","冲动前的一点犹豫是好事，先想清楚代价，再决定要不要跳。",
    "Let go of over-planning today and take a step on instinct — even without a clear destination, moving is what opens the way.","A pause before you leap is wise here — weigh the cost first, then decide if it's worth it."],
  ["d/de/RWS_Tarot_01_Magician.jpg","魔术师","The Magician","把握资源，化想法为现实","能力被浪费，言行不一","Resourceful, turning ideas into reality","Wasted potential, saying one thing and doing another",
    "你手上其实握着足够的资源和技能，今天是把想法真正落地的好时机，别再等待完美条件。","空谈计划却迟迟不动手，容易让机会溜走；先做一件小事，动力会跟上来。",
    "You already have the resources and skill you need — today's a good day to turn an idea into something real instead of waiting for perfect conditions.","Talking about plans without acting risks letting the moment pass — do one small thing and momentum will follow."],
  ["8/88/RWS_Tarot_02_High_Priestess.jpg","女祭司","The High Priestess","倾听直觉，探索内在智慧","忽视直觉，秘密浮现","Trust your intuition, seek inner wisdom","Ignoring instinct, hidden truths surface",
    "答案未必在外部，静下心倾听内心的直觉，今天的判断力比平时更敏锐。","别忽略那些欲言又止的信号，有些事情你其实已经知道答案，只是不愿承认。",
    "The answer may not be out there — quiet your mind and trust your gut, your instincts are sharper than usual today.","Don't ignore what's left unsaid — you may already know the answer and just aren't ready to admit it."],
  ["d/d2/RWS_Tarot_03_Empress.jpg","皇后","The Empress","丰盛滋养，创造与美好","过度付出，创造力受阻","Abundance, nurturing creativity","Overgiving, creativity blocked",
    "今天适合照顾自己和身边的人，一点滋养和耐心会带来意想不到的丰盛感。","别把所有精力都给了别人，先把自己照顾好，才有余力去创造和给予。",
    "A good day to nurture yourself and those around you — a little care and patience brings unexpected abundance.","Don't pour all your energy into others — take care of yourself first so you have something left to create and give."],
  ["c/c3/RWS_Tarot_04_Emperor.jpg","皇帝","The Emperor","秩序稳固，掌控与责任","专断固执，失去掌控","Stability, structure and responsibility","Rigid control, losing your grip",
    "今天适合把混乱的事情理出秩序，主动承担责任会让你更有掌控感。","控制欲太强反而会让事情失控，试着放松一点，给别人一点空间。",
    "A good day to bring order to something chaotic — stepping up and taking charge will give you a real sense of control.","Gripping too tightly can backfire — ease up a little and give others some room."],
  ["8/8d/RWS_Tarot_05_Hierophant.jpg","教皇","The Hierophant","传统指引，值得学习请教","挑战常规，不拘一格","Guidance from tradition, worth learning","Breaking convention, an unconventional path",
    "遇到拿不准的事，不妨请教有经验的人，今天适合学习而不是单打独斗。","别被条条框框束缚住，有些规矩今天可以灵活变通一下。",
    "If you're unsure about something, ask someone with experience — today favors learning over going it alone.","Don't let rules box you in — some of them can bend a little today."],
  ["d/db/RWS_Tarot_06_Lovers.jpg","恋人","The Lovers","真心连接，面临重要抉择","关系失衡，价值观冲突","A true connection, a key choice ahead","Imbalance, clashing values",
    "今天的选择关乎你真正在意的东西，跟着心意走，而不是别人的期待。","关系里如果有一方在勉强迎合，不如坦白说出真实想法，减少内耗。",
    "Today's choice touches on what actually matters to you — follow your own heart, not someone else's expectations.","If one side of a relationship is stretching to accommodate the other, honesty now beats quiet resentment later."],
  ["9/9b/RWS_Tarot_07_Chariot.jpg","战车","The Chariot","意志坚定，乘胜前行","方向迷失，失去掌控","Willpower, driving forward to victory","Lost direction, losing control",
    "目标清晰、意志坚定，今天适合放手去做，阻力会比想象中小。","方向感有点模糊时，先停一停，别在错的路上加速。",
    "Your goal is clear and your resolve is strong — push forward today, resistance will be lighter than you expect.","If your sense of direction feels shaky, pause before you speed up — don't accelerate on the wrong road."],
  ["f/f5/RWS_Tarot_08_Strength.jpg","力量","Strength","以柔克刚，内在勇气","自我怀疑，力不从心","Gentle courage, inner strength","Self-doubt, feeling depleted",
    "面对棘手的人或事，温和而坚定比强硬对抗更管用，你的耐心是今天的武器。","别对自己太苛刻，力不从心的时候，休息也是一种力量。",
    "With a difficult person or situation, gentle firmness works better than force — patience is your strength today.","Go easy on yourself — when you're running low, resting is its own kind of strength."],
  ["4/4d/RWS_Tarot_09_Hermit.jpg","隐士","The Hermit","独处反思，寻求内在真理","过度孤立，逃避现实","Solitude and reflection, seeking truth","Isolation, avoiding reality",
    "今天适合一个人静静想清楚一些事，答案往往在独处时才会浮现。","别把自己关得太久，适度地走出去和人聊聊，会有新的视角。",
    "Today favors quiet reflection alone — answers tend to surface in solitude, not in the noise.","Don't stay closed off too long — stepping out and talking to someone could bring a fresh perspective."],
  ["3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg","命运之轮","Wheel of Fortune","转折降临，顺势而为","时运不济，抗拒变化","A turning point, go with the flow","Bad timing, resisting change",
    "变化正在发生，顺着势头走，比硬撑着控制结果更明智。","如果事情暂时不顺，别太焦虑，风向迟早会转。",
    "Change is already in motion — riding the momentum is wiser than trying to force the outcome.","If things feel off right now, don't panic — the tide will turn in time."],
  ["e/e0/RWS_Tarot_11_Justice.jpg","正义","Justice","公平决断，承担后果","有失公允，逃避责任","Fair judgment, owning the consequences","Unfairness, avoiding accountability",
    "今天适合把账算清楚，无论是道歉还是讨回公道，诚实面对会让你更轻松。","在下判断前，先确认自己掌握了全部事实，避免因为片面信息误伤别人。",
    "A good day to settle the books — whether it's an apology or setting the record straight, honesty will lighten your load.","Before you judge, make sure you have the full picture — acting on partial information could hurt someone unfairly."],
  ["2/2b/RWS_Tarot_12_Hanged_Man.jpg","倒吊人","The Hanged Man","换个视角，以退为进","徒劳挣扎，拖延不前","A new perspective, yielding to move forward","Futile struggle, stuck in delay",
    "如果一件事怎么想都想不通，换个角度或者暂时放下，答案会自己出现。","别在原地死磕太久，有些坚持其实只是在拖延该做的决定。",
    "If something isn't clicking no matter how you look at it, step back or shift your angle — the answer will find you.","Don't dig in too long on the same spot — some stubbornness is really just delaying a decision you need to make."],
  ["d/d7/RWS_Tarot_13_Death.jpg","死神","Death","旧的结束，新的开始","抗拒转变，停滞不前","An ending, and a new beginning","Resisting change, stuck in place",
    "一个阶段正在结束，与其抗拒，不如坦然放手，为新的开始腾出空间。","抓着不肯放的东西，可能正是拖住你前进的原因，试着松开手。",
    "One chapter is closing — accept it rather than resist, and make room for what comes next.","What you're holding onto so tightly may be exactly what's holding you back — try letting it go."],
  ["f/f8/RWS_Tarot_14_Temperance.jpg","节制","Temperance","调和平衡，循序渐进","失衡过度，缺乏耐心","Balance, gradual progress","Excess, running short on patience",
    "今天不适合走极端，把节奏放慢一点，事情会自然而然找到平衡。","最近是不是哪方面有点用力过猛了？适当收一收，别把自己耗尽。",
    "This isn't a day for extremes — slow the pace and things will find their own balance.","Have you been pushing too hard in one direction lately? Pull back a little before you burn out."],
  ["5/55/RWS_Tarot_15_Devil.jpg","恶魔","The Devil","被欲望束缚，需要自省","挣脱枷锁，重获自由","Bound by desire, time for self-reflection","Breaking free, regaining your freedom",
    "留意那些让你欲罢不能却让你不舒服的习惯，今天适合诚实面对自己被什么困住了。","你比自己想象中更有力量摆脱旧习惯，今天可以试着迈出第一步。",
    "Notice the habits that hook you but don't actually feel good — today's a day for being honest about what's trapping you.","You have more power to break free of an old pattern than you think — today's a good day to take the first step."],
  ["5/53/RWS_Tarot_16_Tower.jpg","高塔","The Tower","剧变降临，旧构崩塌","危机暂时延后，缓慢重建","Sudden upheaval, old structures fall","Crisis delayed, slow rebuilding",
    "有些变化来得突然且猛烈，但它其实是在拆掉一个早就该拆的旧结构。","危机可能被暂时压下来了，趁现在有余力，主动去处理一直被回避的问题。",
    "Change may hit suddenly and hard, but it's tearing down a structure that was overdue for it.","A crisis may be simmering rather than resolved — use this calmer window to face what you've been avoiding."],
  ["d/db/RWS_Tarot_17_Star.jpg","星星","The Star","希望重燃，疗愈前行","信心动摇，方向模糊","Hope renewed, healing forward","Wavering confidence, unclear direction",
    "经过一段不容易的时期后，今天带来一点喘息和希望，允许自己相信事情会好起来。","信心低落的时候，先从一件小小的、能做到的事情开始重建它。",
    "After a rough stretch, today brings a little room to breathe — allow yourself to believe things can get better.","When confidence is low, rebuild it with one small thing you know you can actually do."],
  ["7/7f/RWS_Tarot_18_Moon.jpg","月亮","The Moon","潜意识浮现，真相朦胧","迷雾渐散，焦虑缓解","The subconscious surfaces, truth is hazy","The fog clears, anxiety eases",
    "有些事情现在看不清楚很正常，不必急着下结论，让直觉慢慢引路。","困扰你的焦虑可能被放大了，试着把担心的事写下来，看清楚它的真实大小。",
    "It's normal not to see things clearly right now — there's no need to rush a conclusion, let intuition lead the way.","The anxiety bothering you may be bigger in your head than in reality — write it down and see its true size."],
  ["1/17/RWS_Tarot_19_Sun.jpg","太阳","The Sun","喜悦成功，充满活力","一时受挫，光芒暂敛","Joy and success, full of energy","A brief setback, dimmed light",
    "今天适合把心里藏着的好消息或好状态大方展现出来，好运正站在你这边。","就算今天没那么顺，也只是暂时的阴天，别让一时的低落掩盖了整体的方向。",
    "A good day to let good news or good energy show — luck is genuinely on your side.","Even if today feels off, it's just a passing cloud — don't let a rough moment overshadow the bigger picture."],
  ["d/dd/RWS_Tarot_20_Judgement.jpg","审判","Judgement","觉醒反思，迎接新生","自我怀疑，逃避召唤","Awakening reflection, embracing rebirth","Self-doubt, avoiding the call",
    "今天适合停下来回顾一下最近的选择，你可能会看清一个一直没意识到的模式。","对自己太严厉的评判不会带来真正的改变，先接纳，再决定要不要调整。",
    "A good day to pause and review your recent choices — you may spot a pattern you hadn't noticed before.","Being too harsh with yourself won't create real change — accept where you are first, then decide what to adjust."],
  ["f/ff/RWS_Tarot_21_World.jpg","世界","The World","圆满完成，达成目标","功亏一篑，尚待收尾","Completion, a goal achieved","Falling just short, unfinished business",
    "一件事快要圆满收尾了，今天适合花点时间为这个阶段画上句号，再迎接下一程。","还差最后一点就完成了，别在这时候松劲，坚持把它做完会很值得。",
    "Something is nearing a satisfying close — take a moment today to mark the ending before starting the next chapter.","You're almost there — don't ease off now, seeing it through to the end will be worth it."]
];

// ========== 小阿卡那：牌组文件映射 ==========
export const SUIT_FILES = {
  Wands: ["1/11/Wands01.jpg","0/0f/Wands02.jpg","f/ff/Wands03.jpg","a/a4/Wands04.jpg","9/9d/Wands05.jpg","3/3b/Wands06.jpg","e/e4/Wands07.jpg","6/6b/Wands08.jpg","4/4d/Tarot_Nine_of_Wands.jpg","0/0b/Wands10.jpg","6/6a/Wands11.jpg","1/16/Wands12.jpg","0/0d/Wands13.jpg","c/ce/Wands14.jpg"],
  Cups: ["3/36/Cups01.jpg","f/f8/Cups02.jpg","7/7a/Cups03.jpg","3/35/Cups04.jpg","d/d7/Cups05.jpg","1/17/Cups06.jpg","a/ae/Cups07.jpg","6/60/Cups08.jpg","2/24/Cups09.jpg","8/84/Cups10.jpg","a/ad/Cups11.jpg","f/fa/Cups12.jpg","6/62/Cups13.jpg","0/04/Cups14.jpg"],
  Swords: ["1/1a/Swords01.jpg","9/9e/Swords02.jpg","0/02/Swords03.jpg","b/bf/Swords04.jpg","2/23/Swords05.jpg","2/29/Swords06.jpg","3/34/Swords07.jpg","a/a7/Swords08.jpg","2/2f/Swords09.jpg","d/d4/Swords10.jpg","4/4c/Swords11.jpg","b/b0/Swords12.jpg","d/d4/Swords13.jpg","3/33/Swords14.jpg"],
  Pents: ["f/fd/Pents01.jpg","9/9f/Pents02.jpg","4/42/Pents03.jpg","3/35/Pents04.jpg","9/96/Pents05.jpg","a/a6/Pents06.jpg","6/6a/Pents07.jpg","4/49/Pents08.jpg","f/f0/Pents09.jpg","4/42/Pents10.jpg","e/ec/Pents11.jpg","d/d5/Pents12.jpg","8/88/Pents13.jpg","1/1c/Pents14.jpg"]
};

// ========== 小阿卡那：牌义 ==========
export const SUITS = [
  {file:"Wands", cn:"权杖", en:"Wands",
    m:[
      ["新机遇与灵感迸发","犹豫不决，错失良机","A new spark, inspiration bursts forth","Hesitation, a missed opportunity",
        "有个新点子若一直放着没试，今天不妨迈出第一步，哪怕只是很小的一步。","犹豫会耗掉热情，先问自己到底在怕什么，再决定要不要行动。",
        "If there's an idea you've been sitting on, today's the day to take a first small step.","Hesitation drains enthusiasm — figure out what you're actually afraid of before deciding whether to act."],
      ["规划未来，眼光长远","计划停滞，缺乏决断","Long-term planning, looking ahead","Plans stalled, indecision",
        "今天适合把长远的计划再想清楚一点，方向定了，脚步会更踏实。","别一直卡在选项之间比较，先选一个方向试试看，比原地打转更有用。",
        "A good day to sharpen a long-term plan — a clearer direction makes every step feel steadier.","Stop weighing every option side by side — picking a direction and testing it beats standing still."],
      ["拓展布局，静待收获","合作受阻，进展缓慢","Expansion underway, awaiting results","Setbacks in collaboration, slow progress",
        "布局已经铺开，今天更多是耐心等待，而不是急着催结果。","如果合作进展不顺，去主动沟通一下，比闷头猜测更有效。",
        "The groundwork is laid — today calls for patience, not rushing the outcome.","If a collaboration feels stuck, a direct conversation will get you further than guessing."],
      ["庆祝团聚，稳固根基","家庭动荡，计划延迟","Celebration, a solid foundation","Domestic upheaval, delayed plans",
        "今天适合和亲近的人庆祝一下小成就，稳固的关系值得被看见。","家里或团队里有点小摩擦也正常，别急着上纲上线。",
        "A good day to celebrate a small win with people close to you — a stable bond deserves to be acknowledged.","A little friction at home or in the team is normal — no need to blow it out of proportion."],
      ["竞争角力，意见纷争","冲突平息，达成妥协","Competition, clashing opinions","Conflict settling, reaching compromise",
        "意见不合很正常，今天试着把争论变成讨论，会得到更好的结果。","有些争执已经没有意义了，及时收手比继续争对错更划算。",
        "Disagreement is natural — turn the argument into a discussion today and you'll get further.","Some fights aren't worth having anymore — walking away beats proving a point."],
      ["凯旋而归，获得认可","成果被质疑，信心受挫","Triumphant return, recognition earned","Success questioned, confidence shaken",
        "你的努力今天可能会被看见和认可，坦然接受这份肯定就好。","别人的质疑不代表你做错了，相信自己一路走来的判断。",
        "Your effort may get noticed today — let yourself receive the recognition without deflecting it.","Someone else's doubt doesn't mean you got it wrong — trust the judgment that got you this far."],
      ["坚守立场，迎难而上","压力过大，难以招架","Holding your ground under pressure","Overwhelmed, struggling to cope",
        "压力从四面八方来也没关系，你比自己以为的更能扛得住。","如果感觉招架不住了，找人搭把手不是软弱，是聪明。",
        "Even if pressure is coming from every direction, you can handle more than you think.","If you're overwhelmed, asking for backup isn't weakness — it's the smart move."],
      ["进展迅速，消息将至","延误受阻，沟通不畅","Fast progress, news on the way","Delays, poor communication",
        "事情今天可能推进得很快，消息或回复会比预期来得早。","进度卡住时，先检查是不是哪个环节沟通没到位。",
        "Things may move quickly today — news or a reply could arrive sooner than expected.","If progress stalls, check whether a message got lost somewhere along the way."],
      ["历经考验，坚持到底","身心俱疲，过度防备","Tested but persevering","Exhausted, overly defensive",
        "已经撑到这里了，再坚持一下，终点比你想的更近。","过度戒备会让你更累，试着放下一点防御心。",
        "You've come this far — hold on a little longer, the finish line is closer than it looks.","Staying overly guarded is exhausting — try letting your defenses down a little."],
      ["负重前行，责任沉重","学会放下，分担压力","Carrying a heavy load of responsibility","Learning to let go, sharing the burden",
        "肩上的担子是不是有点多了？今天适合分一部分出去。","学着说不，不是所有责任都必须由你一个人扛。",
        "Is your load a little heavier than it should be? Today's a good day to hand some of it off.","Learn to say no — not every responsibility has to be yours alone."],
      ["热情探索，带来消息","三分钟热度，冲动行事","Eager exploration, news arriving","Fleeting enthusiasm, acting on impulse",
        "有个新想法让你跃跃欲试，今天适合去打听、去问、去探索。","别只是三分钟热度，先给这个念头一点时间沉淀。",
        "A new idea has you eager to explore — today's good for asking questions and digging in.","Don't let it be a passing spark — give the idea a little time to settle first."],
      ["勇往直前，行动力强","鲁莽冲动，虎头蛇尾","Bold and driven, full of momentum","Reckless, starts strong but fades",
        "行动力很强的一天，想到就去做，别给自己太多犹豫的时间。","冲得太快容易半途而废，节奏放慢一点会走得更远。",
        "Momentum is strong today — act on it before you talk yourself out of it.","Rushing in too fast risks fizzling out — a steadier pace will take you further."],
      ["自信独立，充满魅力","嫉妒多疑，情绪化","Confident and magnetic","Jealous, doubting, emotional",
        "今天你的自信和状态都很好，大方展现自己不需要犹豫。","如果感到嫉妒或不安，先看清楚那份情绪到底在说什么。",
        "Your confidence is in a good place today — let it show without second-guessing.","If jealousy or unease shows up, look closer at what that feeling is actually telling you."],
      ["果断领导，愿景清晰","专断强势，缺乏耐心","Decisive leadership, clear vision","Domineering, running short on patience",
        "今天适合做决定、定方向，你的判断力比你以为的更靠谱。","别把强势当成解决问题的唯一方式，试着听听不同的声音。",
        "A good day to make the call and set the direction — your judgment is more solid than you think.","Force isn't the only way to solve a problem — make room for a different point of view."]
    ]},
  {file:"Cups", cn:"圣杯", en:"Cups",
    m:[
      ["新的情感，内心丰盈","情感压抑，错失连接","New feelings, an overflowing heart","Suppressed emotion, a missed connection",
        "心里有些柔软的情绪正在生长，允许自己去感受，不用急着定义它。","如果一直压着某种感受，找个安全的方式让它被看见。",
        "A tender new feeling is taking shape — let yourself feel it without rushing to name it.","If you've been bottling up a feeling, find a safe way to let it be seen."],
      ["心意相通，关系和谐","误会渐生，关系失衡","Mutual understanding, harmony","Growing misunderstanding, imbalance",
        "今天适合和某个人好好聊聊，坦诚的交流会让关系更靠近。","关系里如果有一方在单方面付出，是时候聊聊真实的感受了。",
        "A good day for an honest conversation with someone — openness will bring you closer.","If one side of a relationship is doing all the giving, it's time to talk about how you actually feel."],
      ["欢聚庆祝，友谊长存","过度放纵，界限模糊","Joyful gathering, lasting friendship","Overindulgence, blurred boundaries",
        "和朋友或伙伴聚一聚吧，这种连接会给你带来能量。","太多的社交或纵容可能让你耗尽，今天适合适度收一收。",
        "Gather with friends or your circle — that connection will recharge you.","Too much socializing or indulgence could drain you — a little moderation helps today."],
      ["心生倦怠，忽视机会","重新振作，把握当下","Growing weary, missing what's offered","Re-engaging, seizing the moment",
        "如果最近对什么都提不起劲，试着重新留意一下身边被忽略的机会。","重新打起精神的时机到了，别再让好机会从眼前溜走。",
        "If you've been feeling flat about everything, look again at an opportunity you may have overlooked.","It's time to re-engage — don't let a good opportunity slip by unnoticed."],
      ["沉溺遗憾，专注失去","释怀过去，看见希望","Dwelling on loss and regret","Letting go, seeing hope again",
        "沉浸在遗憾里没关系，但记得抬头看看还剩下的东西。","是时候把过去放下了，前面还有值得期待的事。",
        "It's okay to sit with regret for a moment, but remember to look up at what's still standing.","It's time to let the past go — there's something ahead worth looking forward to."],
      ["怀旧温情，重逢旧识","困于过去，不愿成长","Nostalgia, reuniting with the past","Stuck in the past, resisting growth",
        "怀旧的心情今天会很浓，联系一个许久未见的老朋友也不错。","别总活在过去的舒适区里，试着往前走一步。",
        "Nostalgia may be strong today — reaching out to an old friend could feel good.","Don't linger too long in the comfort of the past — try taking a step forward."],
      ["选择众多，幻想丛生","认清现实，做出抉择","Too many choices, fantasy overload","Facing reality, making a decision",
        "选项太多容易让人迷失，今天先弄清楚自己真正想要的是什么。","幻想该落地了，挑一个方向，然后真正开始行动。",
        "Too many options can be dizzying — get clear on what you actually want today.","It's time to bring the daydream down to earth — pick a direction and actually start."],
      ["离开安逸，追寻意义","犹豫不前，逃避问题","Leaving comfort behind to find meaning","Hesitating, avoiding the issue",
        "如果一件事已经不再让你满足，离开它去寻找更有意义的东西并不可惜。","别再逃避那个一直没解决的问题了，直面它会让你轻松很多。",
        "If something no longer feels fulfilling, walking away to find something more meaningful isn't a waste.","Stop dodging the issue you've been avoiding — facing it head-on will lighten the load."],
      ["心愿达成，满足自得","表面满足，内心空虚","A wish fulfilled, contentment","Surface satisfaction, inner emptiness",
        "今天的满足感是实打实的，好好享受这份来之不易的安稳。","表面上的满足如果掩盖了内心的空虚，值得停下来问问自己真正需要什么。",
        "Today's sense of satisfaction is real — enjoy the stability you've earned.","If surface contentment is hiding something emptier underneath, it's worth asking what you actually need."],
      ["家庭圆满，情感丰盛","家庭失和，期望落空","Family harmony, emotional fulfillment","Family discord, unmet expectations",
        "和家人或最亲近的人相处的时光会格外温暖，好好珍惜。","家里的分歧别憋着不说，坦诚沟通比表面和气更重要。",
        "Time with family or or the people closest to you feels especially warm today — savor it.","Don't let a disagreement at home go unspoken — honest talk beats forced harmony."],
      ["直觉敏锐，带来好消息","情绪不稳，不切实际","Sharp intuition, good news coming","Emotional instability, unrealistic ideas",
        "留意今天出现的一点小小灵感或消息，它可能比看起来更重要。","情绪有点飘忽也没关系，给自己一点时间稳下来。",
        "Pay attention to a small piece of inspiration or news today — it may matter more than it seems.","It's okay if your mood feels a bit unsteady — give yourself time to settle."],
      ["浪漫追求，以情动人","情绪化，言行不一","Romantic pursuit, leading with feeling","Moody, words not matching actions",
        "今天适合浪漫地表达心意，真诚的举动会打动对方。","承诺前先看清楚对方的言行是否一致，别被表面打动。",
        "A good day for a heartfelt gesture — sincerity will land well today.","Before committing, check whether words and actions actually match up."],
      ["温柔体贴，情感细腻","过度敏感，情绪泛滥","Gentle and emotionally attuned","Overly sensitive, emotions overflow",
        "你的温柔和体贴今天会成为别人依靠的力量，别觉得这是理所当然。","照顾别人之前，先确认自己的情绪杯子没有见底。",
        "Your warmth today may be exactly what someone leans on — don't take that for granted.","Before caring for others, make sure your own emotional cup isn't running empty."],
      ["情绪成熟，善解人意","情感压抑，操控他人","Emotional maturity, understanding others","Suppressed feelings, manipulating others",
        "面对情绪起伏时保持冷静，你比自己以为的更懂得如何处理它。","别把情绪都藏起来装作没事，找个信任的人说说也没关系。",
        "Staying calm through emotional ups and downs today — you handle it better than you give yourself credit for.","Don't hide everything behind a calm face — it's okay to talk to someone you trust."]
    ]},
  {file:"Swords", cn:"宝剑", en:"Swords",
    m:[
      ["思路清晰，真相浮现","思维混乱，判断失误","Clarity of mind, truth revealed","Confused thinking, poor judgment",
        "今天头脑格外清醒，适合做需要理性判断的决定。","信息不全时先别急着下结论，多问一句会避免误判。",
        "Your mind is unusually clear today — good for decisions that need cold logic.","Don't jump to conclusions with incomplete information — one more question could save you a mistake."],
      ["左右为难，寻求平衡","逃避抉择，信息不明","Caught between two choices, seeking balance","Avoiding the decision, unclear information",
        "拿不定主意的事今天可以先搁一搁，答案会在你不那么焦虑时出现。","逃避这个决定只会让它拖得更久，试着面对它。",
        "If you can't decide, it's okay to set it aside — the answer often shows up once you stop forcing it.","Avoiding this decision will only drag it out longer — try facing it instead."],
      ["心碎伤痛，直面创伤","伤口愈合，重新振作","Heartbreak, facing the wound","Healing, moving forward again",
        "如果心里有个还没愈合的伤口，今天允许自己感受它，而不是压下去。","痛苦正在慢慢过去，你已经在恢复的路上了。",
        "If there's an old wound that hasn't healed, let yourself feel it today instead of pushing it down.","The pain is easing — you're further along in healing than you realize."],
      ["暂缓休整，恢复能量","被迫复出，休息不足","Time to rest, restoring energy","Forced back to action, not enough rest",
        "身心都需要一点喘息，今天允许自己慢下来休息一下。","休息得不够就被迫重新上阵，会更累，尽量先补一补。",
        "Mind and body both need a breather — give yourself permission to slow down today.","Being pushed back into action without enough rest only makes things harder — try to recover first."],
      ["争胜心切，两败俱伤","放下争执，寻求和解","Fighting to win, a hollow victory","Letting go of conflict, seeking peace",
        "有些争论就算赢了也不值得，今天想想这场争执到底为了什么。","放下这场没意义的争执，主动求和会让你更轻松。",
        "Some arguments aren't worth winning — think about what this one is really costing you.","Let go of a pointless conflict — offering peace first will feel lighter than holding your ground."],
      ["渡过难关，迈向平静","难以离开，滞留原地","Moving past hardship, toward calm","Struggling to leave, stuck in place",
        "正在慢慢驶离一段艰难的时期，前方会更平静一些。","如果还没准备好离开某个阶段，慢慢来也没关系。",
        "You're slowly moving past a difficult stretch — calmer waters are ahead.","If you're not quite ready to leave a phase behind, that's okay — there's no rush."],
      ["谋略行事，需防欺瞒","真相败露，坦诚以对","Acting with strategy, watch for deceit","Truth exposed, choosing honesty",
        "今天做事可以聪明一点，但别对身边的人耍心机。","有些没说出口的真相今天可能会浮出水面，坦诚会比隐瞒更轻松。",
        "Being clever today is fine — just don't play games with the people around you.","An unspoken truth may surface today — honesty will feel lighter than keeping it hidden."],
      ["作茧自缚，受限己见","挣脱束缚，重获自由","Self-imposed limits, trapped by your own view","Breaking free, regaining freedom",
        "困住你的可能不是处境本身，而是你看待它的角度，试着换个想法。","你比自己以为的更自由，那些限制很多是自己给的。",
        "What's trapping you may not be the situation itself but how you're viewing it — try a different angle.","You're freer than you think — many of the limits are ones you placed on yourself."],
      ["忧虑焦躁，夜不能寐","放下焦虑，寻求帮助","Anxious, sleepless with worry","Releasing anxiety, seeking support",
        "深夜的胡思乱想常常比现实更吓人，今天试着把担心写下来看看。","别一个人扛着焦虑，找人说说会让它变得没那么沉重。",
        "Late-night worry is usually scarier than reality — try writing down what's bothering you.","Don't carry the anxiety alone — talking it through will make it feel lighter."],
      ["触底反弹，痛苦终结","拖延痛苦，抗拒结束","Hitting bottom, the pain finally ends","Prolonging the pain, resisting closure",
        "最难的部分已经过去了，今天是触底反弹的起点。","别再拖着不肯让这件事结束，痛快地翻篇会更好。",
        "The hardest part is already behind you — today marks the turning point.","Stop dragging this out — a clean ending will serve you better than a slow one."],
      ["求知好奇，消息将至","八卦是非，言语伤人","Curious and alert, news is coming","Gossip and rumor, hurtful words",
        "好奇心今天会带你发现一些有用的信息，多问几个问题。","别被没有根据的传言影响判断，先核实再下结论。",
        "Curiosity leads you to something useful today — ask a few more questions than usual.","Don't let an unverified rumor sway your judgment — check the facts first."],
      ["雷厉风行，直言不讳","鲁莽冲动，考虑不周","Swift and outspoken, acting decisively","Reckless, not thinking things through",
        "今天适合直接了当地表达想法，拖泥带水反而更累。","话说得太快容易伤人，说之前先想一想。",
        "Speak your mind directly today — beating around the bush will only tire you out more.","Words spoken too fast can wound — take a beat before you say them."],
      ["理性独立，一针见血","尖锐刻薄，过于冷漠","Rational and independent, cuts to the truth","Sharp-tongued, overly cold",
        "你今天看事情特别透彻，相信自己的判断，不用委婉。","犀利的话语今天要留意分寸，别让它变成伤人的武器。",
        "Your read on things is unusually sharp today — trust it, no need to soften it.","Watch how sharp your words get today — don't let honesty turn into a weapon."],
      ["权威理性，公正决断","冷酷苛刻，滥用权力","Authoritative and fair-minded","Harsh and unforgiving, misusing power",
        "今天适合做公正而理性的决定，别被情绪左右判断。","权威不等于强硬，今天试着多一点体谅。",
        "A good day for a fair, clear-headed decision — don't let emotion cloud it.","Authority doesn't have to mean harshness — a little more compassion goes a long way today."]
    ]},
  {file:"Pents", cn:"星币", en:"Pentacles",
    m:[
      ["新的机遇，物质起步","错失良机，基础不稳","A new opportunity, material footing","A missed chance, shaky foundation",
        "一个实实在在的新机会今天可能出现，别让它悄悄溜走。","基础没打牢之前，先别急着扩张，稳一稳更重要。",
        "A tangible new opportunity may show up today — don't let it slip by unnoticed.","Before the foundation is solid, hold off on expanding — stability comes first."],
      ["灵活应变，平衡多头事务","顾此失彼，失去平衡","Adapting with ease, balancing priorities","Spread too thin, losing balance",
        "手上事情有点多，今天试着找到一个能兼顾的节奏。","同时抓太多东西容易顾此失彼，先放下一件，喘口气。",
        "You're juggling a lot right now — today's about finding a rhythm that can hold it all.","Trying to hold too much at once means something slips — set one thing down and breathe."],
      ["团队协作，精益求精","配合不佳，标准松散","Teamwork, refining the craft","Poor coordination, low standards",
        "和团队一起打磨一件事，今天的配合会比单打独斗更有效。","如果合作总不顺畅，直接聊聊各自的期待会有帮助。",
        "Refining something together with your team works better than going solo today.","If teamwork keeps hitting snags, a direct talk about expectations will help."],
      ["稳固积累，注重安全感","过度守财，固步自封","Steady accumulation, valuing security","Overly guarded, stuck in place",
        "今天适合把手头的资源稳一稳，安全感值得被认真对待。","抓得太紧反而会错过流动带来的机会，试着松一松手。",
        "A good day to secure what you have — that sense of stability is worth taking seriously.","Holding too tight can block the flow of new opportunity — try loosening your grip."],
      ["困顿失落，感到被排除","走出困境，重获支持","Hardship, feeling left out","Emerging from difficulty, support returns",
        "如果最近感觉被落下了，记得你并不是真的孤立无援。","困难的日子正在过去，帮助也许比你想的更近。",
        "If you've been feeling left out lately, remember you're not as alone as it feels.","The hard stretch is passing — support may be closer than you think."],
      ["慷慨分享，互助共赢","施受失衡，附带条件","Generosity, mutual support","Uneven giving, strings attached",
        "今天适合给予或接受帮助，付出和收获会自然地流动。","帮助如果附带条件，值得想想这份关系是否平等。",
        "A good day to give or receive help — the exchange flows naturally today.","If help comes with strings attached, it's worth asking whether the relationship is truly equal."],
      ["耐心耕耘，静待成果","投入未见回报，需重新评估","Patient cultivation, awaiting results","Effort without reward, time to reassess",
        "已经投入的努力还没到收成的时候，耐心一点，成果在路上。","如果一直看不到回报，值得停下来重新评估方向。",
        "The effort you've invested hasn't ripened yet — stay patient, results are on the way.","If the payoff still isn't showing, it's worth pausing to reassess the direction."],
      ["专注技艺，精进不懈","敷衍了事，缺乏动力","Focused craftsmanship, steady improvement","Going through the motions, lacking drive",
        "今天适合沉下心把一件事做精，专注本身就是一种成就。","如果对手头的事提不起劲，先想想问题出在哪，而不是硬撑。",
        "A good day to focus and refine something — the focus itself is an achievement.","If you can't muster interest in the task at hand, figure out why instead of forcing through it."],
      ["独立富足，享受成果","过度依赖，孤立无援","Independent and comfortable, enjoying the results","Overly dependent, isolated",
        "享受一下靠自己的努力换来的从容，这份独立值得骄傲。","过度依赖别人会让你更不安，试着为自己重新建立一点掌控感。",
        "Enjoy the ease you've earned through your own effort — that independence is worth being proud of.","Leaning too much on others can leave you feeling unsteady — try reclaiming a bit of control for yourself."],
      ["家族传承，长久稳定","家庭纷争，财务隐患","Family legacy, lasting stability","Family conflict, financial risk",
        "今天适合想想长远的稳定，家人或团队的支持会是你的底气。","钱或家庭上的分歧别拖着不谈，及时沟通能省去很多麻烦。",
        "A good day to think about long-term stability — support from family or your team is your foundation.","Don't let a money or family disagreement go unspoken — a timely conversation saves a lot of trouble."],
      ["脚踏实地，学习新技能","计划落空，缺乏耐心","Grounded, learning a new skill","Plans falling through, impatience",
        "今天适合学一项新技能，脚踏实地的积累会有回报。","计划落空时别气馁，把它当成调整方向的机会。",
        "A good day to pick up a new skill — steady groundwork pays off.","If a plan falls through, don't get discouraged — treat it as a chance to adjust course."],
      ["稳扎稳打，勤恳务实","固执僵化，进展缓慢","Steady and diligent, methodical","Stubborn and rigid, slow progress",
        "稳扎稳打是今天最好的策略，慢一点没关系，走得稳更重要。","太固执地守着老方法，可能会让你错过更好的路径。",
        "Steady and methodical is the best approach today — slow is fine as long as it's solid.","Clinging too stubbornly to the old way might mean missing a better path."],
      ["务实温暖，善于持家","过度操劳，忽视自我","Practical and warm, a natural homemaker","Overworked, neglecting self-care",
        "今天照顾好身边的人和事会让你很有成就感，但别忘了也照顾自己。","长期的操劳该被看见了，今天给自己留一点空间休息。",
        "Taking care of the people and things around you feels rewarding today — just don't forget yourself.","Long-running overwork deserves to be acknowledged — carve out some space to rest today."],
      ["富足稳重，慷慨可靠","物质至上，固执贪婪","Prosperous and reliable, generous","Materialistic, stubborn and greedy",
        "今天适合稳健地做决定，你的可靠会让身边人感到安心。","别把物质条件当成衡量一切的唯一标准，多留意其他更重要的东西。",
        "A good day for steady, grounded decisions — your reliability puts others at ease.","Don't let material success be the only measure that matters — make room for what else counts."]
    ]}
];

// ========== 牌序编号 ==========
export const RANK_CN = ["首牌","二","三","四","五","六","七","八","九","十","侍从","骑士","王后","国王"];
export const RANK_EN = ["Ace","Two","Three","Four","Five","Six","Seven","Eight","Nine","Ten","Page","Knight","Queen","King"];

// ========== 生成完整牌组 ==========
function buildDeck(){
  const deck = [];
  MAJOR.forEach(([file,cn,en,up,rev,up_en,rev_en,up_detail,rev_detail,up_detail_en,rev_detail_en])=>{
    deck.push({file, cn, en, up, rev, up_en, rev_en, up_detail, rev_detail, up_detail_en, rev_detail_en});
  });
  SUITS.forEach(suit=>{
    const files = SUIT_FILES[suit.file];
    suit.m.forEach((pair, i)=>{
      deck.push({
        file: files[i],
        cn: suit.cn + RANK_CN[i],
        en: RANK_EN[i] + " of " + suit.en,
        up: pair[0],
        rev: pair[1],
        up_en: pair[2],
        rev_en: pair[3],
        up_detail: pair[4],
        rev_detail: pair[5],
        up_detail_en: pair[6],
        rev_detail_en: pair[7]
      });
    });
  });
  return deck;
}

export const DECK = buildDeck();

// ========== 工具函数：生成图片URL ==========
export function imgUrl(file){
  return "https://upload.wikimedia.org/wikipedia/commons/" + file;
}

// ========== UI 多语言文案 ==========
export const UI = {
  zh: {
    eyebrow: "今日占卜",
    hint: "轻触卡牌，抽出今日的一张",
    journalLabel: "抽签簿",
    emptyJournal: "还没有记录，抽过的牌会留在这里",
    footerPrefix: "每天的第一次抽牌会被记住 · ",
    resetBtn: "重新抽取（测试用）",
    orient: { up: "正位", rev: "逆位" },
    seal: { up: "正", rev: "逆" },
    insight: " · 今日提示",
    detailLabel: "卡牌详细解读",
    aiLoading: "塔罗师正在凝视卡牌。。。",
    aiFailed: "塔罗师小爱今天休息。",
    weekdays: ["日","一","二","三","四","五","六"],
    dateFmt: (d)=> d.getFullYear() + "年" + (d.getMonth()+1) + "月" + d.getDate() + "日 · 星期" + UI.zh.weekdays[d.getDay()]
  },
  en: {
    eyebrow: "Today's Reading",
    hint: "Tap the card to draw today's reading",
    journalLabel: "Journal",
    emptyJournal: "No draws yet — they'll appear here",
    footerPrefix: "Your first draw each day is remembered · ",
    resetBtn: "Redraw (test)",
    orient: { up: "Upright", rev: "Reversed" },
    seal: { up: "Up", rev: "Rev" },
    insight: " · Today's Insight",
    detailLabel: "Card Detailed Reading",
    aiLoading: "The tarot reader is gazing at the card...",
    aiFailed: "The tarot little love is resting today.",
    weekdays: ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],
    months: ["January","February","March","April","May","June","July","August","September","October","November","December"],
    dateFmt: (d)=> UI.en.months[d.getMonth()] + " " + d.getDate() + ", " + d.getFullYear() + " · " + UI.en.weekdays[d.getDay()]
  }
};

// ========== 月份缩写 ==========
export const MONTH_ABBR = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
